#!/usr/bin/env python3
"""
Batch extract multiple papers from a directory of PDFs.
With progress bars, auto-summary, and aggregated report generation.

Usage:
  python3 batch_extract.py <input_dir> [--output-dir <dir>] [--summarize] [--template <path>]

  --output-dir:    Output directory (default: <input_dir>/extracted)
  --summarize:     Auto-generate summaries using the template
  --template:      Path to summary template (default: ../references/summary-template.md)
  --concurrency:   Number of parallel extractions (default: 4)
"""

import os
import sys
import glob
import subprocess
import json
import re
import argparse
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

# =============================================================================
# Logging
# =============================================================================

def setup_logging(verbose: bool = False):
    level = logging.DEBUG if verbose else logging.INFO
    format_str = '%(asctime)s [%(levelname)s] %(message)s'
    logging.basicConfig(level=level, format=format_str, datefmt='%H:%M:%S')
    return logging.getLogger(__name__)

logger = logging.getLogger(__name__)

# =============================================================================
# Progress Bar
# =============================================================================

def progress_bar(current: int, total: int, prefix: str = '', length: int = 30):
    """Simple text progress bar."""
    percent = current / total
    filled = int(length * percent)
    bar = '█' * filled + '░' * (length - filled)
    return f"{prefix} [{bar}] {current}/{total} ({percent*100:.1f}%)"

# =============================================================================
# Extraction Worker
# =============================================================================

def extract_single_pdf(pdf_path: str, output_dir: str, extract_script: str, timeout: int = 120) -> dict:
    """Extract a single PDF and return result."""
    name = os.path.splitext(os.path.basename(pdf_path))[0]
    # Sanitize filename
    name = re.sub(r'[^\w\-_.]', '_', name)
    out_file = os.path.join(output_dir, f"{name}.md")
    
    try:
        result = subprocess.run(
            [sys.executable, extract_script, pdf_path, '--output', out_file, '--metadata'],
            capture_output=True, text=True, timeout=timeout
        )
        if result.returncode == 0:
            return {'file': os.path.basename(pdf_path), 'output': out_file, 'status': 'ok'}
        else:
            return {'file': os.path.basename(pdf_path), 'status': 'error', 'error': result.stderr.strip()}
    except subprocess.TimeoutExpired:
        return {'file': os.path.basename(pdf_path), 'status': 'timeout'}
    except Exception as e:
        return {'file': os.path.basename(pdf_path), 'status': 'error', 'error': str(e)}

# =============================================================================
# Auto-Summary Generator
# =============================================================================

def generate_summary(paper_content: str, template_path: str) -> str:
    """Generate a summary from extracted content using the template."""
    # Read template
    if os.path.exists(template_path):
        with open(template_path, 'r', encoding='utf-8') as f:
            template = f.read()
    else:
        # Default minimal template
        template = """# Paper Summary

## TL;DR

## Background

## Method

## Results

## Limitations
"""

    # Extract basic info from content
    title = "Unknown"
    lines = paper_content.split('\n')
    for i, line in enumerate(lines):
        if line.startswith('# '):
            title = line[2:].strip()
            break
    
    # Extract abstract
    abstract = ""
    in_abstract = False
    for line in lines:
        if 'abstract' in line.lower():
            in_abstract = True
            continue
        if in_abstract and line.strip():
            abstract += line.strip() + " "
        if in_abstract and len(abstract) > 500:
            break
    
    # This is a placeholder - actual summary would be generated by AI
    summary = f"""# {title}

> Generated summary (placeholder - requires AI for full summary)

**Note**: This is an automated extraction. Full summary generation requires AI analysis.

---

## Extracted Content Preview

{abstract[:500]}...

---

*Extracted on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
    
    return summary

# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description='Batch extract PDFs to Markdown with optional summarization')
    parser.add_argument('input_dir', help='Directory containing PDF files')
    parser.add_argument('--output-dir', '-o', default=None,
                        help='Output directory (default: <input_dir>/extracted)')
    parser.add_argument('--summarize', '-s', action='store_true',
                        help='Auto-generate summaries after extraction')
    parser.add_argument('--template', '-t', default=None,
                        help='Path to summary template')
    parser.add_argument('--concurrency', '-c', type=int, default=4,
                        help='Number of parallel extractions (default: 4)')
    parser.add_argument('--timeout', type=int, default=120,
                        help='Timeout per paper in seconds (default: 120)')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Verbose output')
    
    args = parser.parse_args()
    global logger
    logger = setup_logging(args.verbose)
    
    input_dir = os.path.abspath(args.input_dir)
    if not os.path.isdir(input_dir):
        logger.error(f"ERROR: {input_dir} is not a directory")
        sys.exit(1)

    output_dir = args.output_dir or os.path.join(input_dir, 'extracted')
    os.makedirs(output_dir, exist_ok=True)

    pdfs = sorted(glob.glob(os.path.join(input_dir, '*.pdf')))
    if not pdfs:
        logger.error(f"No PDF files found in {input_dir}")
        sys.exit(1)

    # Find extract script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    extract_script = os.path.join(script_dir, 'extract_paper.py')
    
    # Find template
    if args.template:
        template_path = args.template
    else:
        template_path = os.path.join(script_dir, '..', 'references', 'summary-template.md')

    logger.info(f"Found {len(pdfs)} PDF(s) in {input_dir}")
    logger.info(f"Output directory: {output_dir}")
    logger.info(f"Concurrency: {args.concurrency}")
    
    results = []
    start_time = datetime.now()
    
    # Parallel extraction
    logger.info("🚀 Starting extraction...")
    
    with ThreadPoolExecutor(max_workers=args.concurrency) as executor:
        futures = {
            executor.submit(extract_single_pdf, pdf, output_dir, extract_script, args.timeout): pdf 
            for pdf in pdfs
        }
        
        completed = 0
        for future in as_completed(futures):
            completed += 1
            result = future.result()
            results.append(result)
            
            # Progress
            bar = progress_bar(completed, len(pdfs), prefix='  ')
            if result['status'] == 'ok':
                logger.info(f"{bar} ✅ {result['file']}")
            else:
                logger.warning(f"{bar} ❌ {result['file']}: {result.get('error', 'error')}")

    # Summary
    ok = sum(1 for r in results if r['status'] == 'ok')
    elapsed = (datetime.now() - start_time).total_seconds()
    
    logger.info(f"\n{'='*50}")
    logger.info(f"📊 Extraction Complete!")
    logger.info(f"   Success: {ok}/{len(pdfs)}")
    logger.info(f"   Failed: {len(pdfs) - ok}")
    logger.info(f"   Time: {elapsed:.1f}s")
    logger.info(f"   Output: {output_dir}")

    # Auto-summarize if requested
    if args.summarize and ok > 0:
        logger.info("\n📝 Generating summaries...")
        
        summary_dir = os.path.join(output_dir, 'summaries')
        os.makedirs(summary_dir, exist_ok=True)
        
        summary_template = ""
        if os.path.exists(template_path):
            with open(template_path, 'r', encoding='utf-8') as f:
                summary_template = f.read()
        
        for result in results:
            if result['status'] != 'ok':
                continue
            
            md_file = result['output']
            name = os.path.splitext(os.path.basename(md_file))[0]
            
            try:
                with open(md_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Generate summary
                summary = generate_summary(content, template_path)
                
                # Save summary
                summary_file = os.path.join(summary_dir, f"{name}_summary.md")
                with open(summary_file, 'w', encoding='utf-8') as f:
                    f.write(summary)
                    
                logger.info(f"   ✅ {name}_summary.md")
            except Exception as e:
                logger.warning(f"   ❌ {name}: {e}")
        
        logger.info(f"\n📁 Summaries saved to: {summary_dir}")

    # Write manifest
    manifest = {
        'extracted_at': datetime.now().isoformat(),
        'input_dir': input_dir,
        'output_dir': output_dir,
        'total': len(pdfs),
        'success': ok,
        'failed': len(pdfs) - ok,
        'elapsed_seconds': elapsed,
        'results': results
    }
    
    manifest_path = os.path.join(output_dir, '_manifest.json')
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    
    logger.info(f"\n📋 Manifest: {manifest_path}")
    logger.info("✨ Done!")


if __name__ == '__main__':
    main()
